on:  ##Triggered once the ‘/rebase’ comment is *added* to the pull request
  issue_comment:
    types: [created] ##When the comment is 'created' then check if it's part of pull request. if so, run.
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      id: checkout-step
      with:
        fetch-depth: 0
    - run: 'echo Created Checkout ${{ steps.checkout-step.outputs.url }}'
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.2
      id: auto-rebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: 'echo Created Rebase ${{ steps.auto-rebase.outputs.url }}'
